from __future__ import annotations

from typing import Protocol

from src.services.types import NormalizedDict


class MarketDataService(Protocol):
    def get_token_context(self, symbol: str) -> NormalizedDict: ...
    def get_wallet_context(self, address: str) -> NormalizedDict: ...
    def get_watch_today_context(self) -> NormalizedDict: ...
    def get_signal_context(self, token: str) -> NormalizedDict: ...
    def get_audit_context(self, symbol: str) -> NormalizedDict: ...
    def get_meme_context(self, symbol: str) -> NormalizedDict: ...
