from __future__ import annotations

from typing import Protocol


class MarketDataService(Protocol):
    def get_token_context(self, symbol: str) -> dict: ...
    def get_wallet_context(self, address: str) -> dict: ...
    def get_watch_today_context(self) -> dict: ...
    def get_signal_context(self, token: str) -> dict: ...
