from __future__ import annotations

# Exit pressure
EXIT_RATE_HIGH = 70
EXIT_RATE_MODERATE = 40

# Top-holder concentration
CONCENTRATION_EXTREME = 80
CONCENTRATION_HIGH = 65
CONCENTRATION_ELEVATED = 60
CONCENTRATION_MEANINGFUL = 45

# Wallet top-position concentration
WALLET_CONCENTRATION_EXTREME = 75
WALLET_CONCENTRATION_HIGH = 50
WALLET_CONCENTRATION_MEANINGFUL = 45

# Liquidity (USD)
LIQUIDITY_DEEP = 50_000_000
LIQUIDITY_MODERATE = 10_000_000
LIQUIDITY_THIN = 1_000_000

# Signal age (hours)
SIGNAL_AGE_STALE = 8
SIGNAL_AGE_AGING = 2
